### ISSUE TITLE
Restore a single file...

### ISSUE THREAD

**Issue by ghost** [MatteoGuadrini/Butterfly-Backup#4]
Hello,

This looks really promising but I would like to be able to restore a single file (or multiple, but not all) from a backup. I've read the documentation and it's not obvious if this is possible. I see the export command could be a possibility but the only option without exporting the whole backup is to use excludes.

Thanks!

**Comment by MatteoGuadrini** [comment]
Add the functionality to restore some only some files to specific backup.
Include this functionality into next release.
For upgrade, see [Readme](https://github.com/MatteoGuadrini/Butterfly-Backup/#installation) for installation
