### ISSUE TITLE
Butterfly Buckup enhancement

### ISSUE THREAD

**Issue by RaghavRao** [MatteoGuadrini/Butterfly-Backup#6]
## Description

Use [ssh-config](https://pypi.org/project/ssh-config/) to parse ssh hosts, edit documentation to differentiate between host aliases configured in ~/.ssh/config vs FQDN hostname

## Impacted action

backup | restore | config

## Proposed names of the parameters (short and long)

* name parameter - maybe add an argument for ssh-host vs FQDN hostname
* possible argument(s) - host

Additional context

**Comment by MatteoGuadrini** [comment]
Hi @RaghavRao, `rsync`, being based on the ssh protocol, looks at the `~/.ssh/config` or `/etc/.ssh/config` file depending on your setup. The control of the active port in Butterfly Backup is based exclusively on the opening of the socket, therefore it cannot consider these files.

The solution I propose is to use the [fabric](https://docs.fabfile.org/en/stable/index.html) package and precisely the `fabric.config.Config` object, with the `load_ssh_config()` method, which loads the aforementioned SSH configuration files. 

In this way it will be possible to have the aliases of the hostnames in these files.

**Comment by MatteoGuadrini** [comment]
Hi @RaghavRao, in the new version `1.10`, I introduce check ssh config that consider sshconfig files.
