### ISSUE TITLE
Butterfly Backup enhancement : text file for the '--custom-data' command ?

### ISSUE THREAD

**Issue by didier33170** [MatteoGuadrini/Butterfly-Backup#8]
## Description

For the 'backup' mode there is an option [File_list.txt] that allow to use a text file in case of several hostnames, to be backed up.
It would be useful to have the same option for the '--custom-data' command. I'm intending to daily backup up to 5 directory trees.In that case the command line starts to be very long, with the full path of each directory, and so difficult to read and to maintained.

## Impacted action

backup

**Comment by MatteoGuadrini** [comment]
Hi @didier33170, 
thanks so much for your suggestion!
This feature is a nice idea. The way I conceived it, it can be implemented in two different ways:
* making the argument accept `--custom-data` as well as path also files (and then treat the files as you indicated)
* making a new argument like `--file-path` and accepting a single file as an argument and processing it (in case the paths inside it are invalid, skip with warning).

Personally I prefer the second choice, given that the unique value of the argument does not allow for errors.
What do you think, could it go?

**Comment by didier33170** [comment]
Hello Matteo. Many thanks for the interest and proposals!
Yes, the second option would be easy to use, like '--file-path [File_list.txt]'. But both options could works. With the second, the risk of error is moved from the command line to the syntax of the .txt file.

**Comment by MatteoGuadrini** [comment]
Added `--file-data` argument on *backup* action into version 1.11.0
